apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontend"
        dapr.io/app-port: "5001"
    spec:
      imagePullSecrets:
      - name: ali-key
      containers:
      - name: frontend
        image: registry.cn-beijing.aliyuncs.com/chester-dapr/frontend:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: Always

